services:
  service1:
    build: ./service1
    ports:
      - "8199:8199"
    environment:
      STORAGE_URL: "http://storage:8200"
      SERVICE2_URL: "http://service2:8198"
      VSTORAGE_PATH: "/var/vstorage/log.txt"
    volumes:
      - ./vStorage:/var/vstorage/log.txt
  service2:
    build: ./service2
    environment:
      STORAGE_URL: "http://storage:8200"
      VSTORAGE_PATH: "/var/vstorage/log.txt"
    volumes:
      - ./vStorage:/var/vstorage/log.txt
  storage:
    build: ./storage
    environment:
      LOG_FILE: "/data/logs/log.txt"
    volumes:
      - storage:/data/logs
volumes:
  storage: